name: Trigger Vercel Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
        
      - name: Deployment Triggered
        run: echo "Vercel deployment has been triggered successfully!"
